Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace team8.Models
{
    public class Customer
    {
        [Key]
        public int CustomerID { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string CustomerFirstName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string CustomerLastName { get; set; }
        [Required]
        [Display(Name = "Address")]
        public string CustomerAddress { get; set; }
        [Required]
        [Display(Name = "City")]
        public string CustomerCity { get; set; }
        [Required]
        [Display(Name = "State")]
        public string CustomerState { get; set; }
        [Required]
        [Display(Name = "Zipcode")]
        public int CustomerZipcode { get; set; }
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string CustomerPhoneNumber { get; set; }
        [Required]
        [Display(Name = "User Name")]
        public string CustomerUserName { get; set; }
        [Required]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string CustomerPassword { get; set; }


        //creating the one to many relationship!!
        public ICollection<Payment> Payment { get; set; }
        public ICollection<Order> Order { get; set; }
        public IEnumerable<Order> _lstOrders { get; set; }



    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Web;
using team8.Models;


namespace team8.Controllers
{
    public class CustomerController : Controller
    {
        //index page
        CustomerDataAccessLayer objCustomer = new CustomerDataAccessLayer();
        [HttpGet]
        public IActionResult Index(int? CustomerID)
        {
            if (Session.CustomerID == 0)
            {
                return RedirectToAction("Index", "Login");
            }

            CustomerID = Session.CustomerID;
            Customer customer = objCustomer.GetCustomerData(CustomerID);
            if (customer != null)
            {
            }
            
            return View(customer);

        }

        //create customer
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //create customer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                objCustomer.AddCustomer(customer);
                Session.CustomerID = customer.CustomerID;
                return RedirectToAction("Index");

            }
            return View(customer);
        }

        //edit customer
        [HttpGet]
        public IActionResult Edit(int? CustomerID)
        {
            if (CustomerID == null)
            { return NotFound(); }

            Customer customer = objCustomer.GetCustomerData(CustomerID);

            if (customer == null)
            { return NotFound(); }
            return View(customer);           
        }

        //edit customer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int CustomerID, [Bind]Customer customer)
        {
            if (CustomerID != customer.CustomerID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                objCustomer.UpdateCustomer(customer);
                return RedirectToAction("Index", new {customer.CustomerID });
            }
            return View(customer);
        }

        //details on single customer
        [HttpGet]
        public IActionResult Details(int? CustomerID)
        {
            if(CustomerID == null)
            {
                return NotFound();
            }

            Customer customer = objCustomer.GetCustomerData(CustomerID);

            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }
        


        [HttpGet]
        public IActionResult ViewAllCustomers()
        {

            {
                List<Customer> lstCustomer = new List<Customer>();
                lstCustomer = objCustomer.GetAllCustomers().ToList();


                return View(lstCustomer);
            }
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using team8.Models;



namespace team8.Controllers
{
    public class OrderController : Controller
    {
        OrderDataLayer objOrder = new OrderDataLayer();
        CatalogDataLayer objCatalog = new CatalogDataLayer();
        PaymentDataLayer objPayment = new PaymentDataLayer();
        CustomerDataAccessLayer objCustomer = new CustomerDataAccessLayer();

        //all orders for a customer
        [HttpGet]
        public IActionResult Index(int CustomerID)
        {
            Order order = new Order();
            order._lstOrders = objOrder.GetAllCustomerOrder(Convert.ToInt32(CustomerID));

            if (order._lstOrders != null)
            {
                TempData["CustomerID"] = CustomerID;

                return View(order);
            }

            else
            {
                return View();
            }

        }
        [HttpPost]
        public IActionResult Index(int CustomerID, string orderType)
        {
            if (ModelState.IsValid)
            {
                Order order = new Order();

                if (orderType == "A")
                {
                    order._lstOrders = objOrder.GetAllCustomerOrder(Convert.ToInt32(CustomerID));
                    return View(order);
                }
                else
                {
                    order._lstOrders = objOrder.CustomerOrderStatus(CustomerID, orderType);
                    return View(order);
                }
            }

            return View();
        }


        //show details for one order
        [HttpGet]
        public IActionResult Details(int? OrderID)
        {
            if (OrderID == null)
            {
                return NotFound();
            }

            Order order = objOrder.GetOrderData(OrderID);
                                 

            if (order == null)
            {
                return NotFound();
            }

            int CardID = order.CardID;
            order.payment = objPayment.GetPaymentData(CardID);

            int CatalogID = order.CatalogID;
            order.catalog = objCatalog.GetOrderCatalog(CatalogID);

            int CustomerID = order.CustomerID;
            order.customer = objCustomer.GetCustomerData(CustomerID);



            return View(order);
        }
                          
    }
}

Views/Customer/Create.cshtml
@model team8.Models.Customer

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>


<h4>Customers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerFirstName" class="control-label">First Name</label>
                <input asp-for="CustomerFirstName" class="form-control" />
                <span asp-validation-for="CustomerFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerLastName" class="control-label">Last Name</label>
                <input asp-for="CustomerLastName" class="form-control" />
                <span asp-validation-for="CustomerLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerAddress" class="control-label">Address</label>
                <input asp-for="CustomerAddress" class="form-control" />
                <span asp-validation-for="CustomerAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerCity" class="control-label">City</label>
                <input asp-for="CustomerCity" class="form-control" />
                <span asp-validation-for="CustomerCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerState" class="control-label">State</label>
                <input asp-for="CustomerState" class="form-control" />
                <span asp-validation-for="CustomerState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerZipcode" class="control-label">Zipcode</label>
                <input asp-for="CustomerZipcode" class="form-control" />
                <span asp-validation-for="CustomerZipcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhoneNumber" class="control-label">Phone Numbe</label>
                <input asp-for="CustomerPhoneNumber" class="form-control" />
                <span asp-validation-for="CustomerPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerUserName" class="control-label">User Name</label>
                <input asp-for="CustomerUserName" class="form-control" />
                <span asp-validation-for="CustomerUserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPassword" class="control-label">Password</label>
                <input asp-for="CustomerPassword" class="form-control" />
                <span asp-validation-for="CustomerPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
            <div>
                <a asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>
<div>

</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Customer/CustomerLogin.cshtml
@model team8.Models.Customer
@{
    ViewData["Title"] = "CustomerLogin";
}

<h2>CustomerLogin</h2>

<div>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CustomerLogin">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="CustomerUserName" class="control-label">Username</label>
                <input asp-for="CustomerUserName" class="form-control" placeholder="Enter Username"/>
                <span asp-validation-for="CustomerUserName" class="text-danger"></span>
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPassword" class="control-label">Password</label>
                <input asp-for="CustomerPassword" class="form-control" placeholder="Password"/>
                <span asp-validation-for="CustomerPassword" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-default" />
                <a asp-controller="Customer" asp-action="Create">Create New User</a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Customer/Delete.cshtml
@model team8.Models.Customer

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employees</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerFirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerFirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerLastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerLastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerCity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerCity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerState)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerState)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerZipcode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerZipcode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerPhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerPhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerUserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerUserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerPassword)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerPassword)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="CustomerID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-controller="Customer"asp-action="ViewAllCustomers">Back to List</a>
    </form>
</div>   

Views/Customer/Details.cshtml
@model team8.Models.Customer

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.CustomerFirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerFirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerLastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerLastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerCity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerCity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerState)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerState)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerZipcode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerZipcode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerPhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerPhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerUserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerUserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerPassword)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerPassword)
        </dd>


    </dl>
    <a asp-controller="Customer"asp-action="Edit" asp-route-CustomerID ="@Model.CustomerID">Edit Information</a>
</div>
<div>
    
    <a asp-action="Index">Return to My Account</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Customer/Edit.cshtml
@model team8.Models.Customer

@{
    ViewData["Title"] = "My Account";
}

<h2>Edit</h2>
<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerID" />
            <div class="form-group">
                <label asp-for="CustomerFirstName" class="control-label">First Name</label>
                <input asp-for="CustomerFirstName" class="form-control" />
                <span asp-validation-for="CustomerFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerLastName" class="control-label">Last Name</label>
                <input asp-for="CustomerLastName" class="form-control" />
                <span asp-validation-for="CustomerLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerAddress" class="control-label">Address</label>
                <input asp-for="CustomerAddress" class="form-control" />
                <span asp-validation-for="CustomerAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerCity" class="control-label">City</label>
                <input asp-for="CustomerCity" class="form-control" />
                <span asp-validation-for="CustomerCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerState" class="control-label">State</label>
                <input asp-for="CustomerState" class="form-control" />
                <span asp-validation-for="CustomerState" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CustomerZipcode" class="control-label">Zipcode</label>
                <input asp-for="CustomerZipcode" class="form-control" />
                <span asp-validation-for="CustomerZipcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhoneNumber" class="control-label">Phone Number</label>
                <input asp-for="CustomerPhoneNumber" class="form-control" />
                <span asp-validation-for="CustomerPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerUserName" class="control-label">User Name</label>
                <input asp-for="CustomerUserName" class="form-control" />
                <span asp-validation-for="CustomerUserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPassword" class="control-label">Password</label>
                <input asp-for="CustomerPassword" class="form-control" />
                <span asp-validation-for="CustomerPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Return to My Account</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
} 

Views/Customer/Index.cshtml
@model team8.Models.Customer

@{
    ViewData["Title"] = "My Account";
}

<h2>My Account</h2>

<h4>Welcome @Html.DisplayFor(model => model.CustomerFirstName) </h4>

<div>
    <hr />
    <div>
        <a asp-controller="Order" asp-action="Index" asp-route-CustomerID="@Model.CustomerID">My Orders</a>
    </div>
    <div>
        <a asp-controller="Payment" asp-action="Index" asp-route-CustomerID="@Model.CustomerID">Payment Information</a>
    </div>
    <div>
        <a asp-controller="Customer" asp-action="Details" asp-route-CustomerID="@Model.CustomerID">My Information</a>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}